### PR TITLE
Add rail-layer collision mask to base pole entities

### PR DESCRIPTION
**Pull request by Blacksmoke16**
I'm no modder but this seems all that was required to update the mod to be Factorio `1.1` compatible.

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
After reading a bit more about this, should `object-layer` be in there at all, or just a hard swap to `rail-layer`?

**Comment by robot256** [comment]
Looks like `object-layer` is used for buildings and power poles that the player and vehicles can collide with.  So it's needed if we don't want cars to drive over catenary poles like they do regular signals.

**Comment by mantikhoras** [comment]
Can we get some traction on this PR?

**Comment by robot256** [comment]
According to the author's forum page, they are no longer maintaining this mod.  Might be time for an adoption.

**Comment by Scarabytes** [comment]
Hey everyone, I'm glad to see that someone has the time to work on updating this mod. If anyone of you is interested in taking over this mod, please message me and I can set you up as contributor both in this github and on the mod portal.

**Comment by mantikhoras** [comment]
@Scarabytes I'd be interested in tinkering with this mod. And while I have you here, is there a way other than gh to pick your brain? It's always useful for me to be able to talk to someone when learning a new code base.

**Comment by Scarabytes** [comment]
You can message me on Discord @Julian#0726, I'm usually quicker to respond there.

@mantikhoras and/or @Blacksmoke16 is this message and the thumbs up a request to be made a contributor? :)

**Comment by Blacksmoke16** [comment]
@Scarabytes No, I use this mod and was easy enough to update; but I'm not in a position to be a long term maintainer.

**Review by Scarabytes — APPROVED** [review]

**Pull request merged**
